name: Android CI

on:
  pull_request:
    paths-ignore:
      - '**.md'
jobs:
  buildDevelopApk:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2.1.0
      - name: Copy CI gradle.properties
        run: |
          mkdir -p ~/.gradle/
          echo "GRADLE_USER_HOME=${HOME}/.gradle" >> $GITHUB_ENV
          echo "org.gradle.jvmargs=-Xmx2m" > ~/.gradle/gradle.properties
      - name: Build with Gradle
        run: ./gradlew --no-daemon assembleDebug
      - name: Archive assembled APK
        uses: actions/upload-artifact@v2
        with:
          name: assembled-develop-apk
          path: app/build/outputs/apk/develop/app-develop.apk

  unitTest:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Copy CI gradle.properties
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2.1.0
      - name: Run UnitTest
        run: ./gradlew --no-daemon testDebugUnitTest

  ktlint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Copy CI gradle.properties
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'zulu'
          java-version: '11'
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2.1.0
      - name: Run Android Lint
        run: ./gradlew --no-daemon lintDebug
